# Tên của workflow, sẽ hiển thị trong tab "Actions" trên GitHub
name: Check FLearning Branch

# Điều kiện để kích hoạt workflow
on:
  # Chạy khi có push code lên nhánh `FLearning`
  push:
    branches:
      - FLearning
  # Chạy khi có Pull Request được mở hoặc cập nhật nhắm vào nhánh `FLearning`
  pull_request:
    branches:
      - FLearning

# Các công việc sẽ được thực hiện
jobs:
  test-build-and-format:
    name: Test, Build and Format Check
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ repo về
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Node.js (chọn phiên bản bạn dùng)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Sửa lại đường dẫn, trỏ vào thư mục con `Flearning_FE`
          cache-dependency-path: 'Flearning_FE/package-lock.json'

      # Bước 3: Cài đặt các dependencies
      # Thêm `working-directory` để chạy lệnh trong thư mục con
      - name: Install dependencies
        run: npm ci
        working-directory: ./Flearning_FE

      # Bước 4: Kiểm tra định dạng code bằng Prettier
      - name: Check code formatting
        run: npm run format:check
        working-directory: ./Flearning_FE

      # Bước 5: Chạy các bài test tự động (Unit Test)
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./Flearning_FE

      # Bước 6: Chạy build production để kiểm tra toàn diện
      - name: Run build
        run: npm run build
        working-directory: ./Flearning_FE
